/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package guicontrol;
/**
 *
 * @author Tiaan
 */
public class GamePanel extends javax.swing.JPanel {

    /**
     * Creates new form ActiveGamePanel
     */
    private GUIController controller;
    private GameLobbyPanel lobbyScreen;
    private Game game;
    
    public GamePanel(GUIController controllerIn) {      //Needs to receive a game object
        initComponents();
        controller = controllerIn;
        lobbyScreen = new GameLobbyPanel(controller);
        this.add(lobbyScreen, 0);
        lobbyScreen.setBounds(0,0,795,577);
        this.validate();
        this.repaint();
    }
    
    public void initializeLobby(String gameName, int asHost) {
        if (asHost == 1)
            lobbyScreen.initializeLobbyAsHost(gameName);
        else {
            lobbyScreen.initializeLobby(gameName);
            lobbyScreen.addToPlayerList("Waiting for host to start...");
        }
    }
    
    public void updateLobbyPlayersList(String playerName, int addName) {
        if (addName == 1)
            lobbyScreen.addToPlayerList(playerName);
        else
            lobbyScreen.removeFromPlayersList(playerName);
    }
    
    public void lobbyMessageSent() {
        lobbyScreen.displaySentMessage();
    }
    
    public void initializeGameScreen() {
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 795, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 577, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables

}
