
package guicontrol;

import java.util.*;
import javax.swing.*;
import javax.swing.JOptionPane;

public class GameForm extends javax.swing.JFrame {

    private GUIController controller;
    private Vector<String> gamesListVector;
    
    public GameForm(GUIController controllerIn) {
        initComponents();
        controller = controllerIn;
        gamesListVector  = new Vector<String>();
        gamesListVector.clear();
        
    }
    
    public void addToGamesList(String gameName) {
        gamesListVector.add(gameName);
        listGamesList.setListData(gamesListVector);
    }
    
    public void clearGamesList() {
        gamesListVector.clear();
        listGamesList.setListData(gamesListVector);
    }
    
    public void displayJoinError() {
        JOptionPane.showMessageDialog(null, "That game is no longer available to join", "Join error",JOptionPane.INFORMATION_MESSAGE);
    }
    
    public void addTab(JPanel newPanel, String gameName) {
        tabbedPanel.addTab(gameName, newPanel);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tabbedPanel = new javax.swing.JTabbedPane();
        pnlGameBrowser = new javax.swing.JPanel();
        scrollPanelGL = new javax.swing.JScrollPane();
        listGamesList = new javax.swing.JList();
        btnRefresh = new javax.swing.JButton();
        btnJoinGame = new javax.swing.JButton();
        btnCreateGame = new javax.swing.JButton();
        tfGameSearch = new javax.swing.JTextField();
        btnGameSearch = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        listGamesList.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        scrollPanelGL.setViewportView(listGamesList);

        btnRefresh.setText("Refresh");
        btnRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefreshActionPerformed(evt);
            }
        });

        btnJoinGame.setText("Join game");
        btnJoinGame.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnJoinGameActionPerformed(evt);
            }
        });

        btnCreateGame.setText("Create new game");
        btnCreateGame.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateGameActionPerformed(evt);
            }
        });

        btnGameSearch.setText("Search for game");
        btnGameSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGameSearchActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlGameBrowserLayout = new javax.swing.GroupLayout(pnlGameBrowser);
        pnlGameBrowser.setLayout(pnlGameBrowserLayout);
        pnlGameBrowserLayout.setHorizontalGroup(
            pnlGameBrowserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlGameBrowserLayout.createSequentialGroup()
                .addGroup(pnlGameBrowserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(scrollPanelGL, javax.swing.GroupLayout.PREFERRED_SIZE, 437, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnlGameBrowserLayout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(tfGameSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(24, 24, 24)
                        .addComponent(btnGameSearch, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlGameBrowserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnCreateGame, javax.swing.GroupLayout.DEFAULT_SIZE, 151, Short.MAX_VALUE)
                    .addComponent(btnRefresh, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnJoinGame, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        pnlGameBrowserLayout.setVerticalGroup(
            pnlGameBrowserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlGameBrowserLayout.createSequentialGroup()
                .addComponent(btnRefresh, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnJoinGame, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCreateGame, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(pnlGameBrowserLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlGameBrowserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tfGameSearch)
                    .addGroup(pnlGameBrowserLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnGameSearch)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(scrollPanelGL, javax.swing.GroupLayout.PREFERRED_SIZE, 382, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        tabbedPanel.addTab("Game Browser", pnlGameBrowser);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tabbedPanel)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tabbedPanel)
        );

        tabbedPanel.getAccessibleContext().setAccessibleName("PanelTab");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshActionPerformed
        controller.requestGamesList(null);
    }//GEN-LAST:event_btnRefreshActionPerformed

    private void btnJoinGameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnJoinGameActionPerformed
        controller.attemptGameJoin((String) listGamesList.getSelectedValue());
    }//GEN-LAST:event_btnJoinGameActionPerformed

    private void btnCreateGameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateGameActionPerformed
        addToGamesList("hello");        //TEST CODE
        controller.gameJoinUnsuccessful();  //TEST CODE
        
    }//GEN-LAST:event_btnCreateGameActionPerformed

    private void btnGameSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGameSearchActionPerformed
        controller.requestGamesList(tfGameSearch.getText());
    }//GEN-LAST:event_btnGameSearchActionPerformed

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCreateGame;
    private javax.swing.JButton btnGameSearch;
    private javax.swing.JButton btnJoinGame;
    private javax.swing.JButton btnRefresh;
    private javax.swing.JList listGamesList;
    private javax.swing.JPanel pnlGameBrowser;
    private javax.swing.JScrollPane scrollPanelGL;
    private javax.swing.JTabbedPane tabbedPanel;
    private javax.swing.JTextField tfGameSearch;
    // End of variables declaration//GEN-END:variables
}
