
package guicontrol;


public class LoginForm extends javax.swing.JFrame {

    private GUIController controller;
    
    public LoginForm(GUIController controllerIn) {
        initComponents();
        controller = controllerIn;
        lblServerError.setVisible(false);
    }
    
    public void activateLogin() {
        btnLogin.setEnabled(true);
        tfUsername.setEnabled(true);
        ptfPassword.setEnabled(true);
        btnConnect.setEnabled(false);
        tfIPadd1.setEnabled(false);
        tfIPadd2.setEnabled(false);
        tfIPadd3.setEnabled(false);
        tfIPadd4.setEnabled(false);
        lblServerError.setVisible(false);
    }
    
    public void displayServerError() {
        lblServerError.setVisible(true);
    }
    
    public void displayLoginError(String errorMsg) {
        lblLoginError.setText(errorMsg);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tfIPadd1 = new javax.swing.JTextField();
        tfIPadd2 = new javax.swing.JTextField();
        tfIPadd3 = new javax.swing.JTextField();
        tfIPadd4 = new javax.swing.JTextField();
        lblIPdot1 = new javax.swing.JLabel();
        lblIPdot2 = new javax.swing.JLabel();
        lblIPdot3 = new javax.swing.JLabel();
        btnConnect = new javax.swing.JButton();
        tfUsername = new javax.swing.JTextField();
        lblUsername = new javax.swing.JLabel();
        lblPassword = new javax.swing.JLabel();
        btnLogin = new javax.swing.JButton();
        lblServerIP = new javax.swing.JLabel();
        lblServerError = new javax.swing.JLabel();
        lblLoginError = new javax.swing.JLabel();
        ptfPassword = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        tfIPadd1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tfIPadd1KeyTyped(evt);
            }
        });

        tfIPadd2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tfIPadd2KeyTyped(evt);
            }
        });

        tfIPadd3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tfIPadd3KeyTyped(evt);
            }
        });

        tfIPadd4.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tfIPadd4KeyTyped(evt);
            }
        });

        lblIPdot1.setText(".");

        lblIPdot2.setText(".");

        lblIPdot3.setText(".");

        btnConnect.setText("Connect to server");
        btnConnect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConnectActionPerformed(evt);
            }
        });

        tfUsername.setEnabled(false);

        lblUsername.setText("Username:");

        lblPassword.setText("Password:");

        btnLogin.setText("Login");
        btnLogin.setEnabled(false);
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });

        lblServerIP.setText("Server IP");

        lblServerError.setText("Unable to connect to server");

        lblLoginError.setText("TEMPTEXT");

        ptfPassword.setEnabled(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblServerError)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblServerIP)
                        .addGap(12, 12, 12)
                        .addComponent(tfIPadd1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblIPdot2))
                    .addComponent(lblPassword)
                    .addComponent(lblUsername))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblLoginError)
                    .addComponent(tfUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(tfIPadd2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblIPdot1, javax.swing.GroupLayout.PREFERRED_SIZE, 4, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(tfIPadd3, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblIPdot3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(tfIPadd4, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(15, 15, 15)
                        .addComponent(btnConnect))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(ptfPassword, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(btnLogin, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 148, Short.MAX_VALUE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfIPadd2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfIPadd3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblIPdot3)
                    .addComponent(lblIPdot1)
                    .addComponent(lblIPdot2)
                    .addComponent(btnConnect)
                    .addComponent(tfIPadd4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblServerIP)
                    .addComponent(tfIPadd1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(lblServerError)
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblUsername))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPassword)
                    .addComponent(ptfPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnLogin)
                .addGap(18, 18, 18)
                .addComponent(lblLoginError)
                .addContainerGap(98, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tfIPadd2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfIPadd2KeyTyped
        if(tfIPadd2.getText().length()>=3)
        {
            tfIPadd2.setText(tfIPadd2.getText().substring(0, 2));
        }
    }//GEN-LAST:event_tfIPadd2KeyTyped

    private void tfIPadd3KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfIPadd3KeyTyped
        if(tfIPadd3.getText().length()>=3)
        {
            tfIPadd3.setText(tfIPadd3.getText().substring(0, 2));
        }
    }//GEN-LAST:event_tfIPadd3KeyTyped

    private void tfIPadd4KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfIPadd4KeyTyped
        if(tfIPadd4.getText().length()>=3)
        {
            tfIPadd4.setText(tfIPadd4.getText().substring(0, 2));
        }
    }//GEN-LAST:event_tfIPadd4KeyTyped

    private void tfIPadd1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfIPadd1KeyTyped
        if(tfIPadd1.getText().length()>=3)
        {
            tfIPadd1.setText(tfIPadd1.getText().substring(0, 2));
        }
    }//GEN-LAST:event_tfIPadd1KeyTyped

    private void btnConnectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConnectActionPerformed
        controller.connectToServer(tfIPadd1.getText() + tfIPadd2.getText() + tfIPadd3.getText() + tfIPadd4.getText());
        activateLogin();    //REMOVE THIS TEST CODE OF FILTH
    }//GEN-LAST:event_btnConnectActionPerformed

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        if ((tfUsername.getText().length() != 0)&&(ptfPassword.getText().length() != 0)) {
            if (tfUsername.getText().matches("[A-Za-z0-9]+"))
                controller.attemptLogin(tfUsername.getText(), ptfPassword.getText());
            else
                displayLoginError("Username can contain only alphanumerical characters");
        }
        else
            displayLoginError("Username or password field can not be empty");
        controller.loginSuccessful();   //REMOVE THIS TEST CODE OF FILTH
   //     controller.loginUnsuccesful("101");   //REMOVE THIS TEST CODE OF FILTH
    }//GEN-LAST:event_btnLoginActionPerformed

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnConnect;
    private javax.swing.JButton btnLogin;
    private javax.swing.JLabel lblIPdot1;
    private javax.swing.JLabel lblIPdot2;
    private javax.swing.JLabel lblIPdot3;
    private javax.swing.JLabel lblLoginError;
    private javax.swing.JLabel lblPassword;
    private javax.swing.JLabel lblServerError;
    private javax.swing.JLabel lblServerIP;
    private javax.swing.JLabel lblUsername;
    private javax.swing.JPasswordField ptfPassword;
    private javax.swing.JTextField tfIPadd1;
    private javax.swing.JTextField tfIPadd2;
    private javax.swing.JTextField tfIPadd3;
    private javax.swing.JTextField tfIPadd4;
    private javax.swing.JTextField tfUsername;
    // End of variables declaration//GEN-END:variables
}
